### ISSUE TITLE
invalid character 'o' looking for beginning of value

### ISSUE THREAD

**Issue by JulianKropp** [gopackage/ddp#12]
I´m trying to connect to a ddp web-socket session of a BigBlueButton Server (https://github.com/bigbluebutton). BigBlueButton uses the Meteor Framework (https://github.com/meteor/meteor). The connection starts with a response from the server which isn't a JSON format. After that the received messages are looking normal.

So first have a look at a normal connection in the browser:
![image](https://user-images.githubusercontent.com/62835694/208422127-f358aabc-29a8-4dde-805e-c812d8fec704.png)

Now I tried to make such a ddp connection:

Code:
```go
	// Connect to the BigBlueButton server over DDP
	client := ddp.NewClient("wss://example.com/html5client/sockjs/079/tblo8e6m/websocket", "https://example.com/html5client/")
	defer client.Close()

	// Connect to the server
	err1 := client.Connect()
	if err1 != nil {
		log.WithError(err1).Fatal("could not connect")
	}
	log.Debug("connected")
	time.Sleep(1 * time.Second)

	// Call the validateAuthToken method with the meetingID, userID, authToken, and userName
	result, err := client.Call("validateAuthToken", []interface{}{meetingID, userID, authToken, userName})
	if err != nil {
		log.WithError(err).Fatal("could not validateAuthToken")
	}

	// Print the result
	fmt.Println(result)
	
	//...
```
Output:
```
2022/12/19 12:07:14 debug connected                
2022/12/19 12:07:14 debug Inbox worker found nil event. May be due to broken websocket. Reconnecting.
2022/12/19 12:07:14  warn Websocket error           error=invalid character 'o' looking for beginning of value
```

I found that the problem is because of the decoder:
https://github.com/gopackage/ddp/blob/1eb8e33af833f8236f41bf783c8a8c793e8fbc1b/client.go#L606

So I tried this. But the result was just a infinite loop:
```go
// inboxManager pulls messages from the inbox and routes them to appropriate
// handlers.
func (c *Client) inboxManager() {
	for {
		select {
		case msg := <-c.inbox:
			// Message!
			//log.Println("Got message", msg)
			msgType, ok := msg["msg"]
			if ok {
				log.WithField("msg", msgType).Debug("recv")
				switch msgType.(string) {
				case "o":
					log.WithField("msg", msg).Debug("Session opened") //<----THIS IS NEW

                               //...
                                
//...

// inboxWorker pulls messages from a websocket, decodes JSON packets, and
// stuffs them into a message channel.
func (c *Client) inboxWorker(ws io.Reader) {
	dec := json.NewDecoder(ws)
	for {
		var event interface{}

		if err := dec.Decode(&event); err == io.EOF {
			break
		} else if err != nil {
			if err.Error() == "invalid character 'o' looking for beginning of value" { //<----THIS IS NEW
				openseasion := map[string]interface{}{
					"msg": "o",
				}
				c.inbox <- openseasion
				continue
			}
			c.errors <- err
		}
		if c.pingTimer != nil {
			c.pingTimer.Reset(c.HeartbeatInterval)
		}
		if event == nil {
			log.Debug("Inbox worker found nil event. May be due to broken websocket. Reconnecting.")
			break
		} else {
			c.inbox <- event.(map[string]interface{})
		}
	}

	c.reconnectLater()
}
```
Output:
```
//...
2022/12/19 11:54:52 debug recv                      msg=o
2022/12/19 11:54:52 debug Session opened            msg=map[msg:o]
2022/12/19 11:54:52 debug recv                      msg=o
2022/12/19 11:54:52 debug Session opened            msg=map[msg:o]
2022/12/19 11:54:52 debug recv                      msg=o
2022/12/19 11:54:52 debug Session opened            msg=map[msg:o]
2022/12/19 11:54:52 debug recv                      msg=o
//...
```

I think only Meteor starts with such a response (`o`) to tell that we can now start sending data. But the `o` at the beginning of the connection is completely irrelevant. So how do I ignore it?

**Comment by badslug** [comment]
@JulianKropp Hi, I'm not familiar with BigBlueButton but from the URL you are using, it looks like they are running DDP on top of a SockJ transport. SockJS opens their sessions with a leading `o` message (as you are seeing) - see their [protocol docs](https://sockjs.github.io/sockjs-protocol/sockjs-protocol-0.3.3.html#section-42). From your web socket dump, it looks like they are transporting everything over SockJS (all their DDP messages are using the `a` SockJS frame) so even if you can get past the session initiation frame, you'll still run into all the other SockJS framing changes to the protocol.

On the plus side, you are on the right track for patching to adjust. I would either find a SockJS go client library, or write a simple wrapper (the SockJS protocol is pretty simple). Make the SockJS wrapper implement io.ReadWriteCloser over the existing web socket and on line 432 of `dip/client.go` inside the `start` method you can substitute the `c.ws = ws` line with your wrapper which could look something like `c.ws = NewSockJS(ws)` where `NewSockJS()` takes the websocket as an argument and returns an io.ReadWriteCloser. Every read would pull the next json array "packet" from SockJS (removed from a SockJS `a` frame) and every write would generate a new json array SockJS frame to send. The library would have to silently consume the SockJS heartbeat frames and handle the SockJS close frame appropriately.

A quick search on pkg.go.dev looks like https://pkg.go.dev/github.com/centrifugal/centrifuge might do the trick for implementing the wrapper (most of the SockJS libraries looks like server implementations rather than a client implementation). But again, it may be easier to just write your own wrapper since SockJS is so simple - I imagine that's the reason why there aren't client libraries available.

Let me know if that makes sense and if you need any further assistance.

**Comment by JulianKropp** [comment]
@badslug First of all. Thank you very much for this detailed answer.
I found out that BigBlueButton uses ddp with both, socketjs and a normal web-socket (if you can describe it like that). So it was possible to connect to the server by just changing the URL.
```go
		// Connect to the BigBlueButton server over DDP
		client := ddp.NewClient("wss://example.com/html5client/websocket", "https://example.com/html5client/")
```

**Comment by badslug** [comment]
Oh, that's great to hear! Glad you got it working.
